### ISSUE TITLE
Subscriptions based on pre-existing polygons

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#656]
https://airtable.com/tbliFUBZhHrWTVy5I/viwjB6S36hfjUz7EU/recZK0D0CisazN09B

### Features
- [x] Support drawing custom polygons over the map, and saving them to local storage or the workspace https://github.com/vizzuality/globalfishingwatch/issues/708
- [ ] Review endpoint for report subscriptions https://github.com/Vizzuality/GlobalFishingWatch/issues/816
- [ ] LImit the number of reportable regions that can be added https://github.com/Vizzuality/GlobalFishingWatch/issues/827
- [ ] UI for AoI list (TO REVIEW) https://github.com/vizzuality/globalfishingwatch/issues/709
- [ ] Periodical report modal UI https://github.com/vizzuality/globalfishingwatch/issues/700
- [ ] Report/alert polygon tooltip https://github.com/vizzuality/globalfishingwatch/issues/699
- [ ] New base UI for reporting https://github.com/vizzuality/globalfishingwatch/issues/698
- [ ] user flag https://github.com/Vizzuality/GlobalFishingWatch/issues/830
