### ISSUE TITLE
Encounters

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#657]
https://airtable.com/tbliFUBZhHrWTVy5I/viwjB6S36hfjUz7EU/recidcBp77HqiaJCO

API endpoints proposal: https://docs.google.com/document/d/1mShlwVt8u5StMSei5kW7z40uwQfhF3oWHP4OnPuIXDA/edit#heading=h.y7iobbv4kin4

Backend repo: https://github.com/Vizzuality/GlobalFishingWatch-vector

- [x] Generator: generate dummy mbtiles dataset from dummy GeoJSON (1)
- [x] Cruncher: revise to acomodate changes from generator + add all processing steps (2)
- [x] add support for multiple zoom levels in cruncher and generator (1)
- [x] Test dummy dataset with frontend `mbtiles branch` (1)(https://github.com/Vizzuality/GlobalFishingWatch/pull/632)
- [x] deliver, and validate with Skytruth, the input GeoJson file used in generator (1)
- [x] rebase mbtiles branch + add branching logic for the client to be able to consume pelagos tiles and PBF tiles at the same time (1)
- [x] Review/fix/merge UI changes https://github.com/Vizzuality/GlobalFishingWatch/pull/780 (5)
- [x] Test/debug/implement new encounters API endpoints (3)
- [ ] Feature flag ? https://github.com/Vizzuality/GlobalFishingWatch/issues/831

**Comment by tiagojsag** [comment]
Clarify: will this be just another layer like the already existing ones (carto or fishing effort), or will it be something new entirely?

**Comment by tiagojsag** [comment]
Propose a design

**Comment by nerik** [comment]
API proposal: https://docs.google.com/document/d/1mShlwVt8u5StMSei5kW7z40uwQfhF3oWHP4OnPuIXDA/edit#heading=h.y7iobbv4kin4
