### ISSUE TITLE
Create a custom AoI to set up alerts

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#687]
https://airtable.com/tbliFUBZhHrWTVy5I/viwjB6S36hfjUz7EU/recs0b7o4eOowNiH

### Features
- [x] Support drawing custom polygons over the map, and saving them to local storage or the workspace https://github.com/vizzuality/globalfishingwatch/issues/708
- [ ] Report/alert polygon tooltip https://github.com/vizzuality/globalfishingwatch/issues/699
- [ ] Allow editing existing custom AoI https://github.com/vizzuality/globalfishingwatch/issues/710 
- [ ] Add AoI from existing layer https://github.com/vizzuality/globalfishingwatch/issues/711
- [ ] Add a configurable limit to the number of vertices a AoI can have. https://github.com/vizzuality/globalfishingwatch/issues/754
